{% set name = "pyvbmc" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyVBMC-{{ version }}.tar.gz
  sha256: d9a59894f6b7ec722d9e81693124ff3b3dd64987e03d1346c08011a21b3726ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - cma >=3.1.0
    - corner >=2.2.1
    - dill >=0.3.5.1
    - gpyreg >=0.1.0
    - imageio >=2.13.5
    - matplotlib-base >=3.5.1
    - numpy >=1.22.1
    - plotly >=5.11.0
    - pytest >=6.2.5
    - pytest-mock >=3.6.1
    - pytest-rerunfailures >=10.2
    - scipy >=1.7.3

test:
  imports:
    - pyvbmc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/PyVBMC/
  doc_url: https://acerbilab.github.io/pyvbmc/
  dev_url: https://github.com/acerbilab/pyvbmc/
  summary: Variational Bayesian Monte Carlo in Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Bobby-Huggins
    - lacerbi
